### PR TITLE
Remove use of `concat()`

### PR DESCRIPTION
**Pull request by fisker**
Leftover from #223

### CODE REVIEW

**Comment by dummdidumm** [comment]
This would be a breaking change because older versions of Prettier (below 2.3 AFAIK) do not support using an array instead of concat. Does Prettier remove support for using concat now or why is this change needed?

**Comment by fisker** [comment]
Ah, I misunderstood #223, it handles new `concat`(array) from  core parsers, not removing `concat()`.

I'm planning to remove `concat()` in Prettier v3.0.0, if you are going to support  older versions of Prettier, we should keep them. 

I got some time today, I was checking plugins listed on Prettier website, I thought it's better to help you remove use of `concat()` before we release v3 (we don't have a schedule yet, maybe longer than I expect).

Feel free to close.

**Comment by dummdidumm** [comment]
Thanks for the clarification! I'll keep this open as a reminder. As soon as Prettier 3.0 is released I'll remove `concat` and release a new major version of `prettier-plugin-svelte` 👍

**Comment by fisker** [comment]
FYI: There is also an ESLint plugin can do this job, [eslint-plugin-prettier-doc](https://github.com/fisker/eslint-plugin-prettier-doc).

**Comment by dummdidumm** [comment]
Closing in favor of #334

**Pull request closed without merging**
