### PR TITLE
Remove bug workaround from README.md

### PR DESCRIPTION
**Pull request by InternetRamen**
[Bug](https://github.com/prettier/prettier/issues/15079) has been fixed

### CODE REVIEW

**Comment by dummdidumm** [comment]
Thank you! I'll wait a few more days until merging to ensure more people are on the latest version

**Comment by InternetRamen** [comment]
Sounds good! Do you mind adding `hacktoberfest-accepted` label to this PR if this goes through?

**Comment by polyzen** [comment]
The fix has not been released yet, it seems.

**Comment by InternetRamen** [comment]
Hmm, I'll check it again. Svelte formatting seems to work for me

**Comment by InternetRamen** [comment]
@polyzen is right, turns out I was using the VSCode extension instead.

**Comment by dummdidumm** [comment]
Closing in favor of #409 - thank you

**Pull request closed without merging**
