### PR TITLE
Support await destructuring

### PR DESCRIPTION
**Pull request by xla**
Svelte 3.20.0 introduced support for await destructing, see sveltejs/svelte#1851 and sveltejs/svelte#4548. This change supports this syntax and keep this plugin functional with the newest svelte version.

### CODE REVIEW

**Comment by rudolfs** [comment]
Lol, approved the wrong PR...

**Comment by andyhot** [comment]
First of all thanks for this!

**prettier-plugin-svelte** currently messes up the `#await` syntax on projects based on svelte > 3.20.

I have code like `{#await orderPayments then payments}` that gets turned into `{#await orderPayments then }` - and even `{:then terms}` becomes `{:then [object Object]}`

I've tested with svelte 3.12 to 3.19 and seen that **prettier-plugin-svelte** works fine there.

The problem i see with this PR is that users of svelte < 3.20 will be affected (their templates will be broken). You can notice this if you apply the PR but downgrade svelte to 3.19 - you'd get test failures.

So, I'm wondering if a) there should be a table documenting which svelte versions are supported by each **prettier-plugin-svelte** release, or b) if it's possible to modify the PR so that it works in all cases (i.e. both pre and post svelte 3.20)

**Comment by aredridel** [comment]
Oof. this is biting me too.

**Comment by andyhot** [comment]
@aredridel you can add something like `"prettier-plugin-svelte": "github:radicle-dev/prettier-plugin-svelte#xla/support-await-destruct"` to your dev dependencies till this is incorporated here

**Comment by Conduitry** [comment]
I haven't tried it yet, but I _think_ this could be made to work with the AST from both older and newer versions of Svelte by making the `expandNode` function check whether `node` is a string and if so returning `' ' + node`.

**Comment by Conduitry** [comment]
The appears to be working. With that change on top of this PR, and using an older version of Svelte, all of the tests pass apart from the ones that using await destructuring (which fail because Svelte can't parse them) - and with that change and using the latest version of Svelte, all these tests still pass.

@xla Can you enable 'allow edits from maintainers' please so that I can push merge resolutions and other fixes to this branch - and won't have to open a new PR and you'll continue to get acknowledgment for your work when this is squashed?

**Comment by xla** [comment]
@Conduitry I don't see that option in the sidebar. Any pointers how to enable it?

**Comment by Conduitry** [comment]
Oh huh apparently this is only available for PRs opened from a fork that belongs to PR opener, and not if it belongs to an org, even one the PR opener is an owner of. That's unfortunate.

**Comment by xla** [comment]
I can ammend changes directly, or invite you as a collaborator on the repo directly. Lemme know which one you prefer @Conduitry

**Comment by Conduitry** [comment]
There were a number of changes, so I'd prefer to be added as a collaborator if you don't mind. Thanks!

**Comment by xla** [comment]
@Conduitry Invite is out. Let me know if I can help in any way to get this done.

**Pull request merged**
