### PR TITLE
Fall back to raw text if there is a parser error in JS

### PR DESCRIPTION
**Pull request by dummdidumm**
Handle default value inside object destructuring that way
#163

### CODE REVIEW

**Comment by Conduitry** [comment]
"Raw text" - does this mean that it won't actually be reformatted? If so, could we instead do something like creating a dummy destructuring to format that we then strip off the unneeded parts of?

**Comment by dummdidumm** [comment]
I did some steps in that direction. It will format such a destructuring if we do `let ${expression} = null`. But then we have to remove the `let` and `= null` from the Doc-Array, which requires some inside knowledge on how the Doc-Structure from the printer looks like. I did not find a quick generic way to cut off the unneeded doc elements.

**Comment by dummdidumm** [comment]
I'm inclined to merge this. It would unblock devs using the default values at the very minimal cost that only that expression is not reformatted, the rest of the document will be. We can always look into a more sophisticated solution later on. Thoughts?

**Comment by Conduitry** [comment]
Yeah, agreed that this partial solution is definitely better than what there is now.

**Pull request merged**
