### PR TITLE
Change svelteSortOrder default to 'scripts-markup-styles'

### PR DESCRIPTION
**Pull request by ayndqy**
Change to match the official svelte template that uses this order.

### CODE REVIEW

**Comment by trbrc** [comment]
I like this, but would it count as a breaking change?

**Comment by ignatiusmb** [comment]
I like this too. I don't think it will necessarily "break" anything just by readjusting the markup order, but it will definitely create a lot of file changes in projects previously tracked and not using this option.

**Comment by trbrc** [comment]
Prettier itself listed changes to configuration defaults as "breaking" and saved them up for the major release earlier this year. https://prettier.io/blog/2020/03/21/2.0.0.html#breaking-changes

I would argue for accepting the change and bumping `prettier-plugin-svelte` to 2.0.0.

**Comment by ryanatkn** [comment]
asked Reddit and Twitter:

<https://www.reddit.com/r/sveltejs/comments/k60egw/which_sort_order_do_you_prefer_for_scripts_styles/>

<https://twitter.com/ryanatkn/status/1334524402487107585>

**Pull request closed without merging**
