### PR TITLE
Keep comments in event handlers

### LINKED ISSUE #96: Comments are removed from inline event listeners
For instance
```jsx
<svelte:body on:keydown={(e) => {
	// hello world
}} />
// -- PRETTIER ->
<svelte:body on:keydown={(e) => {}} />
```

### LINKED ISSUE #99: "Unexpected closing tag" error
When formatting the following code

    <div class="account" >
      <div class="accounttitle" >
        <p >Account</p>
            <DynamicTooltip content={$t(message) || ''} >
            <Icon icon={{ name: 'info_outline' }}  />
              </DynamicTooltip >
      </div >
    </div >
     
    <script>
      /* JavaScript goes here... */
    </script>

I get an error:

      9 |  
    SyntaxError: Unexpected closing tag "DynamicTooltip". It may happen when the tag has already 
    been closed by another tag. For more info see 
    https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (6:7)
      4 |         <DynamicTooltip content={$t(message) || ''} >
      5 |         <Icon icon={{ name: 'info_outline' }}  />
    > 6 |       </DynamicTooltip >
        |       ^
      7 |   </div >
      8 | </div >

If  don't use `||` in the 4th line of the original code, the error doesn't appear.

I'm using the latest version of Prettier from GitHub, and version 1.1.0 of prettier-plugin-svelte

### PR DESCRIPTION
**Pull request by trbrc**
Fixes #96. Includes test that failed before, but is green now.

### CODE REVIEW

**Comment by trbrc** [comment]
In case it helps the review of this PR, here’s a short summary of what the problem was and why this is the solution. Apparently Prettier handles comments in a special way. As far as I can understand, since the formatting will change line wraps, it can affect the legal placement of end-of-line comments in significant ways. So it appears that the comments are collected separately from the main AST and put back in valid locations in a later phase.

To handle expressions in template markup, `prettier-plugin-svelte` wraps the expression in parentheses. (I guess this is so the parser doesn’t interpret a function expression as a function statement?). When removing these parens again it only returns the expression AST without the comments, which must be an oversight. The result is that the comments are lost completely in the output.

The fix simply picks out the comments from the AST and includes them in the returned object.

Let me know if there’s anything else I can do to push this PR along.

**Comment by dummdidumm** [comment]
This keeps the comments, but `/* ... */` somehow get prepended to the next code line:
```html
<button
    on:click={() => {
        /* Event handler with comment */
        const a = 1;
    }}>
    toggle
</button>
```
gets
```html
<button
    on:click={() => {
        /* Event handler with comment */ const a = 1;
    }}>
    toggle
</button>
```

Could you add a test for this and check why this happens? If you don't find out why I'm inclined to still merge because a comment prepended is still better than no comment. 
Could you also add a test for `// ...` comments?

**Comment by ehrencrona** [comment]
I just tested this; the `//` unfortunately doesn't work and the reason is the same as that newline disappearing: the `expressionParser` adds parenthesis around the expression, but that makes all the offsets in the parser wrong, so when it tries to retrieve the commenting style (` */`) it actually retrieves (`*/\n`). This is even worse with `//` which it would turn into ` / `. That was quite messy to debug.

I created #133 that fixes the expression parser too. or you can add those fixes to this PR if you prefer.

**Comment by dummdidumm** [comment]
Thank you for your effort @trbrc ! I decided to go with @ehrencrona's PR.

**Pull request closed without merging**
