### PR TITLE
(fix) replace flatMap (node 11+) with flatten util

### PR DESCRIPTION
**Pull request by dummdidumm**

### CODE REVIEW

**Comment by dummdidumm** [comment]
.. or we just keep it as is but require at least node 11. @ehrencrona thoughts?

**Comment by Conduitry** [comment]
I would vote for this PR rather than doing a major version bump and requiring Node 11. (I'm not sure whether there's already been a release that contains this code, but if so, it would be irresponsible not to release another patch fix even if we decided to go forward with a major version that notes the newer Node requirement.) I'd also vote for running CI on the oldest version of Node we say we support, to catch issues like this earlier.

**Comment by dummdidumm** [comment]
`flatMap` apparently came in through #78, so since May. I agree with you, I'll merge this in.

**Comment by ehrencrona** [comment]
Since it’s also only about a single function that’s easy to replace I agree.

**Pull request merged**
