### PR TITLE
format MustacheTag in pre

### PR DESCRIPTION
**Pull request by hyrious**
- (fix) format MustacheTag in pre

Also added test case.

### CODE REVIEW

**Review by dummdidumm — CHANGES_REQUESTED** [review]
Could you please remove all unrelated changes, like bumping the workflow file or package.json version bumps? Please also remove the removal of `concat` - this plugin is backwards compatible with a version of prettier where `concat` was the only way of constructing an AST array.

**Comment by hyrious** [comment]
> Could you please remove all unrelated changes, like bumping the workflow file or package.json version bumps? Please also remove the removal of `concat` - this plugin is backwards compatible with a version of prettier where `concat` was the only way of constructing an AST array.

Fine, will do it tomorrow.

**Comment by hyrious** [comment]
I'm ready.

**Review by dummdidumm — CHANGES_REQUESTED** [review]
Thanks, this looks way better!

I see two problems with this approach:
1. This only works for mustache tags which are part of the first children, the text. But it's valid to have tags inside pre, for example you could write `<pre>asd<code>const asd = {variable  };</code>asd</pre>`. In this case with the presented solution, `variable  ` wouldn't be formatted

2. This breaks mustache tags where it shouldn't, if the print width in one line is longer than allowed. For example this input:
```svelte
<pre>Hello,
  world!   {JSON.stringify({   foo:'bar'},null,
  2)}Goodbye.
  this text goes waaaaaaaaaaaaaaaaaaaaaaaaaaaaaayyyyyyyyyyyyyyyyyyyyyyyyyyy above the print width {{a: true}} and the mustache should split it
</pre>
```
should print 
```svelte
<pre>Hello,
  world!   {JSON.stringify({ foo: "bar" }, null, 2)}Goodbye.
  this text goes waaaaaaaaaaaaaaaaaaaaaaaaaaaaaayyyyyyyyyyyyyyyyyyyyyyyyyyy above the print width {{
        a: true,
    }} and the mustache should split it
</pre>
```
but it prints
```svelte
<pre>Hello,
  world!   {JSON.stringify(
        { foo: "bar" },
        null,
        2
    )}Goodbye.
  this text goes waaaaaaaaaaaaaaaaaaaaaaaaaaaaaayyyyyyyyyyyyyyyyyyyyyyyyyyy above the print width {{
        a: true,
    }} and the mustache should split it
</pre>
```

I don't have a good answer to both of these problems, so I'm inclined to leave the current logic as-is and don't format mustache tags inside `<pre>` tags.

**Comment by hyrious** [comment]
I see. However I still think there exists some solution to them:
1. let me add more `printPre` to these `isPreTagContent` codes.
2. line breaks in pre should be replaced with `hardline`. the example code you post is because "Goodbye.\n  this text goes..." being treated as one element in prettier.

**Comment by dummdidumm** [comment]
If the code doesn't end up being too big or too complex, then I'm okay with that. On a general note: Prettier HTML formatting doesn't format anything inside `<pre>` tags either, so I would be ok with this being a limitation which we don't handle.

**Comment by hyrious** [comment]
It seems to be easier than I thought.

**Review by dummdidumm — APPROVED** [review]
Thank you! This now formats everything except text inside `pre` tags now which I hope is the correct behavior. Let's see.

**Pull request merged**
